version: "3.7"

services:
    postgres-db:
        hostname: postgres
        image: postgres:13
        container_name: postgres-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: twitter
            POSTGRES_USER: master
            POSTGRES_PASSWORD: masterkey

    rust-twitter:
        image: rust-twitter:1.0
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres-db
        container_name: rust-twitter
        ports:
            - 3000:3000
        environment:
            DATABASE_URL: postgres://master:masterkey@postgres-db/twitter
